name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run:  echo "Hello World!"
      - name: Multiline
        run:  |
              echo  "Hello"
              echo  "How are you"
      - name: Print Goodbye
        run:  echo "Done - bye!"
